# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADMM_c <- function(X, H, U, V, index, Matrix_index1, Matrix_index2, sizes1, sizes2, M1, M2, w, p, n, nk, gamma, tau, num_iter = 100L) {
    .Call(`_ConvexClust_ADMM_c`, X, H, U, V, index, Matrix_index1, Matrix_index2, sizes1, sizes2, M1, M2, w, p, n, nk, gamma, tau, num_iter)
}

ComputeWeights_c <- function(X, mu) {
    .Call(`_ConvexClust_ComputeWeights_c`, X, mu)
}

edges_c <- function(w, n) {
    .Call(`_ConvexClust_edges_c`, w, n)
}

